version: "3.3"
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=flexql_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pilot

volumes:
  db-data: